spring:
  liquibase:
    enabled: true
    contexts: dev
  datasource:
    url: ${URL_DB:jdbc:postgresql://localhost:5432/postgres}
    username: ${USERNAME_DB:postgres}
    password: ${PASSWORD_DB:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        format_sql: false
        show_sql: false
    open-in-view: false